---
title: "Article APO"
output: github_document
---

### Définition de la variable et affichage des fichiers

```{r}
path <- "~/article-apo/Fichierdesequences"
list.files(path)
data<-read.table(file = "/home/rstudio/article-apo/SraRunTable.txt", header = TRUE, sep=",") # Création de la table de données
```

### Utiliser une colonne des métadonnées pour définir le nom des échantillons

```{r}
fnFs <- sort(list.files(path, pattern="_1.fastq.gz", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_2.fastq.gz", full.names = TRUE))
print(fnFs)
print(fnRs)
```

```{r}
sample.names <- (data$Sample.Name)
sample.names
```

```{r}
plotQualityProfile(fnFs[1:2])
```

```{r}
plotQualityProfile(fnRs[1:2])
```

### Filtrer et rogner

```{r}
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
```

```{r}
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE) 
head(out)
```

```{r}

```














